=== Khambrin/LineaCasaBari/data/Desideri.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" >
<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>

    <xs:element name="Liste" type="Tipo_liste"/>
    	
    <xs:complexType name="Tipo_liste">
    	<xs:sequence>
    		<xs:element name="Lista" type="Tipo_lista" maxOccurs="unbounded"/>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Tipo_lista">
    	<xs:sequence>
    		<xs:element name="Utente" type="xs:string"/>
    		<xs:element name="Prodotto" type="xs:string" maxOccurs="unbounded"/>
    	</xs:sequence>
    </xs:complexType>

</xs:schema>

=== Khambrin/LineaCasaBari/data/Desideri.xml
<?xml version="1.0" encoding="UTF-8"?>
<Liste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Desideri.xsd"><Lista><Utente>abari@gmail.com</Utente><Prodotto>678</Prodotto><Prodotto>679</Prodotto></Lista><Lista><Utente>navid@gmail.com</Utente><Prodotto>680</Prodotto><Prodotto>681</Prodotto></Lista></Liste>
